name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build (documentation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the doc framework
        run: |
          make install

      - name: Build docs
        run: |
          make html PROJECT=ibm

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: _build
